OK = 0

STATE_SAVE_INTERVAL = 300

RETURN_CODES = {
   -1   : "BSEC_E_DOSTEPS_INVALIDINPUT - Input sensor id not in valid range",
   -2   : "BSEC_E_DOSTEPS_VALUELIMITS - Input sensor value out of range",
   -6   : "BSEC_E_DOSTEPS_DUPLICATEINPUT - Duplicate input sensor ids",
   -10  : "BSEC_E_SU_WRONGDATARATE - Output sample rate is zero",
   -12  : "BSEC_E_SU_SAMPLERATELIMITS - Output sample rate invalid",
   -13  : "BSEC_E_SU_DUPLICATEGATE - Duplicate output sensor ids",
   -14  : "BSEC_E_SU_INVALIDSAMPLERATE - Sample rate outside global limits",
   -15  : "BSEC_E_SU_GATECOUNTEXCEEDSARRAY - Insufficient buffer for sensor settings",
   -16  : "BSEC_E_SU_SAMPLINTVLINTEGERMULT - Sample rate not correct multiple",
   -17  : "BSEC_E_SU_MULTGASSAMPLINTVL - Gas sensor rate mismatch",
   -18  : "BSEC_E_SU_HIGHHEATERONDURATION - Measurement duration too long",
   -32  : "BSEC_E_PARSE_SECTIONEXCEEDSWORKBUFFER - Work buffer too small",
   -33  : "BSEC_E_CONFIG_FAIL - Configuration failed",
   -34  : "BSEC_E_CONFIG_VERSIONMISMATCH - Version mismatch",
   -35  : "BSEC_E_CONFIG_FEATUREMISMATCH - Feature mismatch",
   -36  : "BSEC_E_CONFIG_CRCMISMATCH - Data corrupted (CRC failed)",
   -37  : "BSEC_E_CONFIG_EMPTY - Config/state too short",
   -38  : "BSEC_E_CONFIG_INSUFFICIENTWORKBUFFER - Work buffer not large enough",
   -40  : "BSEC_E_CONFIG_INVALIDSTRINGSIZE - String size mismatch",
   -41  : "BSEC_E_CONFIG_INSUFFICIENTBUFFER - Output buffer too small",
   -100 : "BSEC_E_SET_INVALIDCHANNELIDENTIFIER - Invalid channel id",
   -104 : "BSEC_E_SET_INVALIDLENGTH - Invalid length",
    2   : "BSEC_I_DOSTEPS_NOOUTPUTSRETURNABLE - No outputs available",
    3   : "BSEC_W_DOSTEPS_EXCESSOUTPUTS - Insufficient output buffer",
    4   : "BSEC_W_DOSTEPS_TSINTRADIFFOUTOFRANGE - Timestamps out of range",
    5   : "BSEC_W_DOSTEPS_GASINDEXMISS - Gas index missing",
    10  : "BSEC_W_SU_UNKNOWNOUTPUTGATE - Unknown output sensor",
    11  : "BSEC_W_SU_MODINNOULP - ULP mode unavailable",
    12  : "BSEC_I_SU_SUBSCRIBEDOUTPUTGATES - No outputs subscribed",
    13  : "BSEC_I_SU_GASESTIMATEPRECEDENCE - Gas estimate has precedence",
    14  : "BSEC_W_SU_SAMPLERATEMISMATCH - Sample rate mismatch",
    100 : "BSEC_W_SC_CALL_TIMING_VIOLATION - Timing violation detected",
    101 : "BSEC_W_SC_MODEXCEEDULPTIMELIMIT - ULP time limit exceeded",
    102 : "BSEC_W_SC_MODINSUFFICIENTWAITTIME - Insufficient wait time",
}
